<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="CommunicationObjectFaultedException.xml" source-language="en-US" target-language="zh-TW">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac557c99eda85bfe1934ce64cb71bbd648cc444d94a.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">57c99eda85bfe1934ce64cb71bbd648cc444d94a</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netcore-1.0,netcore-1.1,netcore-2.0,netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7,xamarinandroid-7.1,xamarinios-10.8,xamarinmac-3.0</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.ServiceModel.CommunicationObjectFaultedException">
          <source>The exception that is thrown when a call is made to a communication object that has faulted.</source>
          <target state="translated">對發生錯誤的通訊物件進行呼叫時，所擲回的例外狀況 (Exception)。</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.ServiceModel.CommunicationObjectFaultedException">
          <source>A <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> is thrown when a call is made to a faulted communication object.</source>
          <target state="translated">對發生錯誤的通訊物件進行呼叫時，會擲回 <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph>。</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.ServiceModel.CommunicationObjectFaultedException">
          <source><ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> is a derived class of <ph id="ph2">&lt;xref:System.ServiceModel.CommunicationException?displayProperty=nameWithType&gt;</ph> and can occur in correct applications.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> 是 <ph id="ph2">&lt;xref:System.ServiceModel.CommunicationException?displayProperty=nameWithType&gt;</ph> 的衍生類別，且會發生在正確的應用程式之中。</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.ServiceModel.CommunicationObjectFaultedException">
          <source>Because typically the code that calls the <ph id="ph1">&lt;xref:System.ServiceModel.ICommunicationObject.Abort%2A?displayProperty=nameWithType&gt;</ph> method reports the error condition that caused the call to <ph id="ph2">&lt;xref:System.ServiceModel.ICommunicationObject.Abort%2A?displayProperty=nameWithType&gt;</ph>, this exception indicates that the call failed but the most useful error information is elsewhere.</source>
          <target state="translated">因為呼叫 <ph id="ph1">&lt;xref:System.ServiceModel.ICommunicationObject.Abort%2A?displayProperty=nameWithType&gt;</ph> 方法的程式碼通常會回報導致呼叫 <ph id="ph2">&lt;xref:System.ServiceModel.ICommunicationObject.Abort%2A?displayProperty=nameWithType&gt;</ph> 的錯誤狀況，所以此例外狀況指出呼叫失敗，但大部分有用的錯誤資訊會存放在其他地方。</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.ServiceModel.CommunicationObjectFaultedException">
          <source>If an object is faulted with several pending calls, only one call throws a specific exception; the others throw <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph>.</source>
          <target state="translated">如果物件因有數個暫止呼叫而發生錯誤，只有一個呼叫會擲回特定的例外狀況，其他呼叫則擲回 <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph>。</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" uid="T:System.ServiceModel.CommunicationObjectFaultedException">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> class.</source>
          <target state="translated">初始化 <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> 類別的新執行個體。</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> class.</source>
          <target state="translated">初始化 <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> 類別的新執行個體。</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor">
          <source>Creates a new <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph>.</source>
          <target state="translated">建立新的 <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph>。</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.String)">
          <source>The message that describes the exception.</source>
          <target state="translated">說明例外狀況的訊息。</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.String)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> class using the specified message.</source>
          <target state="translated">使用指定的訊息，初始化 <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> 類別的新執行個體。</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.String)">
          <source>Creates a new <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> using the specified <ph id="ph2">`message`</ph>.</source>
          <target state="translated">使用指定的 <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph>，建立新的 <ph id="ph2">`message`</ph>。</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The serialization information used to create the exception object.</source>
          <target state="translated">用來建立例外狀況物件的序列化 (Serialization) 資訊。</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The context within which the exception object is created.</source>
          <target state="translated">建立例外狀況物件所在的內容。</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> class when deserializing a stream using the specified <ph id="ph2">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph> and <ph id="ph3">&lt;see cref="T:System.Runtime.Serialization.StreamingContext" /&gt;</ph> objects.</source>
          <target state="translated">在還原序列化資料流時，使用指定的 <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> 和 <ph id="ph2">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph> 物件來初始化 <ph id="ph3">&lt;see cref="T:System.Runtime.Serialization.StreamingContext" /&gt;</ph> 類別的新執行個體。</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>This constructor is called when deserializing a <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> object from a stream.</source>
          <target state="translated">從資料流還原序列化 <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> 物件時，會呼叫這個建構函式 (Constructor)。</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.String,System.Exception)">
          <source>The exception message.</source>
          <target state="translated">例外狀況訊息。</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.String,System.Exception)">
          <source>The inner exception.</source>
          <target state="translated">內部例外狀況。</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.String,System.Exception)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> class using the specified message and inner exception.</source>
          <target state="translated">使用指定的訊息和內部例外狀況，初始化 <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> 類別的新執行個體。</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.String,System.Exception)">
          <source>Creates a new <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> using the specified <ph id="ph2">`message`</ph> and <ph id="ph3">`innerException`</ph>.</source>
          <target state="translated">使用指定的 <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> 與 <ph id="ph2">`message`</ph> 來建立新的 <ph id="ph3">`innerException`</ph>。</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>